// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw1zmQxZaA58MfRrvhgOe4YbxX93weCcA',
    appId: '1:157536481487:web:57eed8bc083223cd14c7ba',
    messagingSenderId: '157536481487',
    projectId: 'mynote-first-proje',
    authDomain: 'mynote-first-proje.firebaseapp.com',
    storageBucket: 'mynote-first-proje.appspot.com',
    measurementId: 'G-W5W7HV8KER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD24E0PkTdnZMaDUjIP-WKcJEkpw657DPk',
    appId: '1:157536481487:android:5de171980f74e9b314c7ba',
    messagingSenderId: '157536481487',
    projectId: 'mynote-first-proje',
    storageBucket: 'mynote-first-proje.appspot.com',
  );
}
